controllers: use Objects.equals() instead of StringUtils.equals()
for Play! 1.6 compatibility:

Compilation error (In {module:openseedbox-common}/app/controllers/BaseController.java around line 100)
The file {module:openseedbox-common}/app/controllers/BaseController.java could not be compiled. Error raised is : The method equals(Object) in the type Object is not applicable for the arguments (String, String)

play.exceptions.CompilationException: The method equals(Object) in the type Object is not applicable for the arguments (String, String)
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:282)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:795)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:639)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:317)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:438)
	at play.Play.preCompile(Play.java:631)
	at play.Play.init(Play.java:324)
	at play.server.Server.main(Server.java:164)

Play! 1.5.3 ... 1.6.0 [0] didn't have related change
for play.mvc.Controller, but the com.h2database dependency got an update
- from 1.4.196 [1] to 1.4.200 [2]!
And checking those javadocs, one could find that
org.h2.util.StringUtils.equals(String, String) just simply disappeared.

The culprit commit h2database/h2database@65d807b landed in 1.4.197.

See openseedbox/openseedbox#62

[0]: https://github.com/playframework/play1/compare/1.5.3...1.6.0
[1]: https://javadoc.io/doc/com.h2database/h2/1.4.196/index.html
[2]: https://javadoc.io/doc/com.h2database/h2/1.4.200/index.html